---
title: myLand
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  countries:
    title: countries
    output: true
defaults:
- scope:
    path: ''
    type: countries
  values:
    layout: country
    name: ''
    price: 0.0
    sku: ''
    image: ''
    weight: 0.0
- scope:
    path: ''
    type: pages
  values:
    layout: page
tagline: Ma dose d'espace vitale
url: flatfile/
snipcart_api_key: OGJkZDE1N2EtODUyNS00OTgzLWE5MzctYzZkM2IxZjBkMTdjNjM2MjA4OTQ2MDI1NTE0OTE0
permalink: pretty
