title: myLand
tagline: Ma dose d'espace vitale

url: flatfile/

snipcart_api_key: ''
timezone: UTC

collections:
  posts:
    title: Posts
    output: true
  countries:
    title: countries
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: countries
  values:
    layout: country
    permalink: "/countries/:title/"
    name: ''
    price: 0.0
    sku: ''
    image: ''
    weight: 0.0
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
